<?php

/**
 * @file
 * Primary module hooks for CUA Theme Suggestions module.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_theme().
 */
function cua_theme_suggestions_theme($existing, $type, $theme, $path)
{
    return [
      'views_view__campuses' => [
        'variables' => [
          'terms' => null,
          'view' => null,
          'rows' => null,
        ],
      ],
      'views_view__interests' => [
        'variables' => [
          'terms' => null,
          'view' => null,
          'rows' => null,
        ],
      ],
    ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Add views field template suggestions.
 * Taken from https://drupal.stackexchange.com/questions/227709/adding-theme-suggestions-programmatically-for-views-rows-fields
 *
 * @inheritdoc
 */
function cua_theme_suggestions_theme_suggestions_views_view(array $variables)
{
    return [
      'views_view_display__' . $variables['view']->current_display,
    ];
}

function template_preprocess_views_view__campuses(&$variables)
{
    $terms = [];
    foreach ($variables["rows"][0]["#rows"] as $row) {
        $terms[] = Term::load($row["#row"]->tid);
    }
    $variables['terms'] = $terms;
}

function template_preprocess_views_view__interests(&$variables)
{
    $terms = [];
    foreach ($variables["rows"][0]["#rows"] as $row) {
        $terms[] = Term::load($row["#row"]->tid);
    }
    $variables['terms'] = $terms;
}

